# Generated by Django 4.0 on 2024-09-09 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round', models.IntegerField(default=1)),
                ('state', models.CharField(choices=[('PLY', 'PLAYED'), ('UPL', 'UNPLAYED')], default='UPL', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('round', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PN', 'PENDING'), ('PG', 'PROGRESS'), ('FN', 'FINISHED')], default='PN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('alias_name', models.CharField(max_length=100, unique=True)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ON', 'ONLINE'), ('OF', 'OFFLINE'), ('IG', 'INGAME')], default='OF', max_length=2)),
                ('championships', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerTournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creator', models.BooleanField(default=False)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('won', models.BooleanField(default=False)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tournament'),
        ),
    ]
