# Generated by Django 4.0 on 2024-09-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playertournament',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='playertournament',
            old_name='tournament_id',
            new_name='tournament',
        ),
    ]
