# Generated by Django 4.0 on 2024-09-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_player_id_playertournament_player_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermatch',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='playermatch',
            old_name='player_id',
            new_name='player',
        ),
    ]
