# Generated by Django 4.0 on 2024-09-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('PN', 'PENDING'), ('PG', 'IN_PROGRESS'), ('FN', 'FINISHED')], default='PN', max_length=2),
        ),
    ]
