# Generated by Django 4.0 on 2024-09-14 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0005_alter_tournament_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profil_photo/%Y/%m/')),
                ('two_factory', models.BooleanField(default=False)),
                ('otp_secret_key', models.CharField(blank=True, max_length=64, null=True)),
                ('alias_name', models.CharField(max_length=100, unique=True)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ON', 'ONLINE'), ('OF', 'OFFLINE'), ('IG', 'INGAME')], default='OF', max_length=2)),
                ('championships', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to='auth.user')),
            ],
        ),
        migrations.AlterField(
            model_name='playermatch',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profil'),
        ),
        migrations.AlterField(
            model_name='playertournament',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profil'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
